// https://vuex.vuejs.org/en/state.html

export default {
  error: '',
  san: {},
  ociRegions: [],
  ociCompartments: [],
  ociInstances: [],
  esxiHosts: [],
  virtualMachines: [],
  instances: [],
  imxComponents: [],
  osPlatforms: [],
  requestedInstances: [],
  expiringComponents: [],
  savedEmails: [],
  languages: [
    { name: 'Arabic' },
    { name: 'Bulgarian' },
    { name: 'Chechen' },
    { name: 'Chinese (Simplified)' },
    { name: 'Chinese (Traditional)' },
    { name: 'Croatian' },
    { name: 'Czech' },
    { name: 'Danish' },
    { name: 'Dutch' },
    { name: 'English' },
    { name: 'English (American)' },
    { name: 'Estonian' },
    { name: 'Finnish' },
    { name: 'Flemish' },
    { name: 'French' },
    { name: 'Georgian' },
    { name: 'German' },
    { name: 'Greek' },
    { name: 'Hebrew' },
    { name: 'Hungarian' },
    { name: 'Italian' },
    { name: 'Japanese' },
    { name: 'Latvian' },
    { name: 'Lithuanian' },
    { name: 'Norwegian' },
    { name: 'Polish' },
    { name: 'Portuguese' },
    { name: 'Portuguese (Brazilian)' },
    { name: 'Romanian' },
    { name: 'Russian' },
    { name: 'Serbian' },
    { name: 'Slovak' },
    { name: 'Slovenian' },
    { name: 'Spanish' },
    { name: 'Spanish (Mexican)' },
    { name: 'Swedish' },
    { name: 'Thai' },
    { name: 'Turkish' },
    { name: 'Vietnamese' },
  ],
};
