version: '3.4'

services:

    node:
        image: ${APACHE_CONTAINER_IMAGE}
        container_name: ${APACHE_CONTAINER_NAME}-${APP_ENV}
        build: docker/apache
        ports:
            - ${APACHE_CONTAINER_HTTP_PORT}:80
            - ${APACHE_CONTAINER_HTTPS_PORT}:443
            - ${APACHE_CONTAINER_SSH_PORT}:22
        volumes:
            - ${APACHE_CONTAINER_VOLUME}:/var/www/html
