version: '3.4'
services:

  web:
    image: ${WEB_CONTAINER_IMAGE:-gitlab.codixfr.private:5005/enterpriseapps/devops-ui:local}
    ports:
      - ${WEB_CONTAINER_IP:-0.0.0.0}:${WEB_CONTAINER_HTTP_PORT:-80}:80
      - ${WEB_CONTAINER_IP:-0.0.0.0}:${WEB_CONTAINER_HTTPS_PORT:-443}:443
    restart: always
    volumes:
      - proxy_config:/etc/nginx/conf.d/proxy

  webssh2:
    image: gitlab.codixfr.private:5005/enterpriseapps/images/webssh2:1.0
    environment:
      WEBSSH2_USERNAME: enterprise
      WEBSSH2_PASSWORD: Sofphia
    restart: always

volumes:
  proxy_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},vers=4,port=${NFS_PORT}"
      device: ":/proxy_config"