version: '3.4'
services:

  web:
    image: ${WEB_CONTAINER_IMAGE:-gitlab.codixfr.private:5005/enterpriseapps/devops-ui:local}
    ports:
      - ${NGINX_CONTAINER_IP:-0.0.0.0}:${NGINX_CONTAINER_HTTP_PORT:-8080}:80
      - ${NGINX_CONTAINER_IP:-0.0.0.0}:${NGINX_CONTAINER_HTTPS_PORT:-4434}:443
    restart: always
    # volumes:
    #   - proxy_config:/etc/nginx/conf.d/proxy

  webssh2:
    build:
      context: ./
      target: webssh2
    ports:
      - ${VUE_APP_WEBSSH2_PORT:-8024}:2222

volumes:
  proxy_config:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},vers=4,port=${NFS_PORT}"
      device: ":/proxy_config"