version: '3.4'

services:

    node:
        image: ${WEB_CONTAINER_IMAGE}
        container_name: ${WEB_CONTAINER_NAME}
        build:
            context: docker/node
            args:
                timezone: ${APP_TIMEZONE}
        ports:
            - ${WEB_CONTAINER_HTTP_PORT}:8080
            - ${WEB_CONTAINER_UI_PORT}:8000
        tty: true
        volumes:
            - ${WEB_CONTAINER_VOLUME}:/var/www/html
        working_dir: /var/www/html
