version: '3.4'

services:

    apache:
        image: ${APACHE_CONTAINER_IMAGE}
        container_name: ${APACHE_CONTAINER_NAME}
        build: docker/apache
        ports:
            - ${APACHE_CONTAINER_IP}:${APACHE_CONTAINER_HTTP_PORT}:80
            - ${APACHE_CONTAINER_IP}:${APACHE_CONTAINER_HTTPS_PORT}:443
            - ${APACHE_CONTAINER_IP}:${APACHE_CONTAINER_SSH_PORT}:22
        volumes:
            - ${APACHE_CONTAINER_VOLUME}:/var/www/html

    webssh2:
        image: ${WEBSSH2_CONTAINER_IMAGE}
        container_name: ${WEBSSH2_CONTAINER_NAME}
        build: docker/webssh2
        ports:
            - ${APACHE_CONTAINER_IP}:${VUE_APP_WEBSSH2_PORT}:2222