version: '3.4'

services:

  web:
    build:
      context: .
      target: base
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: nodemodules
        target: /app/node_modules
        volume:
          nocopy: true

volumes:
  nodemodules:
